version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: chore

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-minor-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: chore
